version: '3.1'

services:

  wordpress:
    build: ./docker/wordpress
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/wp-content/plugins/tuja
      - ./docker/wp-uploads:/var/www/html/wp-content/uploads
    env_file:
      - .env

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: