version: '3.1'

services:

  wordpress:
    build: ./docker/wordpress
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./web:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/tuja
    env_file:
      - .env

  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: