version: '3.1'

services:

  wordpress:
    build: ./docker/wordpress
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./docker/volumes/wordpress:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/tuja
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file:
      - .env

  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env

volumes:
  db_data: