version: '3.1'

services:

  wordpress:
    image: wordpress:4.9.5-php7.0
    depends_on: 
      - db
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/wp-content/plugins/tuja
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data:
  database:
